### ISSUE TITLE
Unable to run i3-gaps on wsl

### ISSUE THREAD

**Issue by mateuszlewko** [Xyene/wsl-dotfiles#1]
How did you manage to run i3-gaps on wsl? For me its always crashing. However i3 installed through apt works fine. Did you apply some hack or do anything special?

**Comment by Xyene** [comment]
I don't think I did anything special for i3-gaps... apart from getting the necessary dependencies to compile it, I don't think I had any issues.

If it's of any help, this is the commit I built i3-gaps off of: https://github.com/Airblader/i3/commit/fdf5d3aacfdfe89b2ea12d3e1aadc7e46c287896, perhaps there's been a breaking change since then.

**Comment by mateuszlewko** [comment]
Yes this commit works! 

Thanks a lot :)

**Comment by Xyene** [comment]
Awesome, glad to hear it worked!
